defaults:
  - model: vfae
  - dataset: adult_vfae

gpus: 1
num_workers: 2
random_seed: 1592334224

training:
  epochs: 100
  batch_size: 100

testing:
  checkpoint: 'outputs/2020-06-10/18-52-06/lightning_logs/version_0/checkpoints/epoch=2.ckpt'
  batch_size: 512
  epochs: 1

loss:
  class: losses.VFAELoss

optimizer:
  class: torch.optim.Adam
  params:
    lr: 1e-3

metrics:
  - loss:
    class: losses.VFAELoss
