defaults:
  - model: vfae
  - dataset: adult_vfae

gpus: 1
num_workers: 4
random_seed: 696665347866991

training:
  epochs: 100
  batch_size: 100
  # checkpointing
  save_ckpts: 5
  monitor: val_discrimination
  mode: min

testing:
  checkpoint: 'multirun/Adult/LogisticRegression/2020-07-01/23-42-19/0/lightning_logs/version_0/checkpoints/epoch=49.ckpt'
  batch_size: 512
  epochs: 1

# set logging paths
hydra:
  run:
    dir: outputs/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  sweep:
    dir: multirun/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/