defaults:
  - model: logistic_regression
  - dataset: adult

gpus: 0
num_workers: 4
random_seed: 1590258941

training:
  epochs: 10
  batch_size: 32

testing:
  checkpoint: 'outputs/2020-06-10/18-52-06/lightning_logs/version_0/checkpoints/epoch=2.ckpt'
  batch_size: 512
  epochs: 1