defaults:
  - model: vfae
  - dataset: adult_vfae

gpus: 1
num_workers: 4
random_seed: 29384753

training:
  epochs: 50
  batch_size: 100
  # checkpointing
  save_ckpts: 5
  monitor: val_discrimination
  mode: min

testing:
  checkpoint:
  batch_size: 512
  epochs: 1

# set logging paths
hydra:
  run:
    dir: outputs/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/
  sweep:
    dir: multirun/${dataset.name}/${model.name}/${now:%Y-%m-%d}/${now:%H-%M-%S}/