model:
  name: LogisticRegression
  class: model.logistic_regression.LogisticRegression
  params:
    in_features: 116
    out_features: 1

loss:
  class: torch.nn.BCEWithLogitsLoss

optimizer:
  class: torch.optim.Adam
  params:
    lr: 1e-3

metrics:
  - accuracy:
    class: metrics.Accuracy
  - discrimination:
    class: metrics.Discrimination
    params:
      use_probabilities: True
  - discrimination:
    class: metrics.Discrimination